"""Options-implied tail risk: fit risk-neutral densities from the WTI
futures option chains and cross-check the market's pricing against the
Hormuz SVAR scenario paths.

Usage: python scripts/options_analysis.py
Writes reports/figures/07_*.png + reports/OPTIONS_TAIL_RISK.md.
Requires data/processed/scenario_paths_usd.csv (run run_all.py first).
"""

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from oil_models import DATA_PROCESSED, FIGURES_DIR, REPORTS_DIR
from oil_models import options_rnd as orx

CPI_ASSUMPTION = 0.025  # annual, to express real scenario paths in nominal USD
REAL_BASE = pd.Timestamp("2025-01-01")  # scenario paths are in 2025-01 USD


def nominal_scenarios() -> pd.DataFrame:
    paths = pd.read_csv(DATA_PROCESSED / "scenario_paths_usd.csv",
                        parse_dates=["date"], index_col="date")
    years = (paths.index - REAL_BASE).days / 365.25
    return paths.mul((1 + CPI_ASSUMPTION) ** years, axis=0)


def smile_figure(chains):
    fig, ax = plt.subplots(figsize=(10, 4.5))
    cmap = plt.cm.viridis(np.linspace(0, 0.85, len(chains)))
    for c, col in zip(chains, cmap):
        sm = orx.otm_smile(c)
        ax.plot(sm.strike, sm.iv, lw=1.5, color=col,
                label=f"{c.label} ({c.days}d, F={c.future:.1f})")
        ax.axvline(c.future, color=col, lw=0.6, ls=":")
    ax.set(xlabel="strike (USD/bbl)", ylabel="implied vol (%)",
           title="WTI OTM implied-vol smiles — quoted mid IV")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "07_iv_smiles.png", dpi=130)
    plt.close(fig)


def density_figure(rnds, scen):
    fig, ax = plt.subplots(figsize=(10.5, 5))
    cmap = plt.cm.viridis(np.linspace(0, 0.85, len(rnds)))
    for r, col in zip(rnds, cmap):
        ax.plot(r.grid, r.density, lw=1.6, color=col,
                label=f"{r.chain.label} ({r.chain.days}d)")
    month = rnds[-1].chain.expiry.to_period("M").to_timestamp()
    if month in scen.index:
        for name, ls in (("full measured loss", "--"),
                         ("50% pass-through", ":")):
            ax.axvline(scen.loc[month, name], color="firebrick", ls=ls, lw=1.3,
                       label=f"SVAR {name} @ {rnds[-1].chain.label} "
                             f"(${scen.loc[month, name]:.0f})")
    ax.set(xlabel="WTI at expiry (USD/bbl)", ylabel="risk-neutral density",
           xlim=(30, 180),
           title="Options-implied densities vs Hormuz SVAR scenario levels")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "07_rnd_densities.png", dpi=130)
    plt.close(fig)


def scenario_prob_table(rnds, scen) -> pd.DataFrame:
    """Market-implied probability of being at/above each SVAR scenario level
    at each expiry."""
    cols = ["25% pass-through", "50% pass-through", "full measured loss"]
    rows = []
    for r in rnds:
        month = r.chain.expiry.to_period("M").to_timestamp()
        if month not in scen.index:
            continue
        row = {"expiry": r.chain.label, "future": r.chain.future}
        for c in cols:
            level = scen.loc[month, c]
            row[f"level: {c}"] = level
            row[f"P(>= {c})"] = r.prob_above(level)
        rows.append(row)
    return pd.DataFrame(rows).set_index("expiry")


def write_report(rnds, tail, probs):
    skew = {r.chain.label: (r.quantile(0.95) - r.chain.future)
            / (r.chain.future - r.quantile(0.05)) for r in rnds}
    lines = [
        "# Options-Implied Tail Risk — WTI Futures Options",
        "",
        "*Auto-generated by `scripts/options_analysis.py` from the option-chain",
        "snapshot in `data/raw/Oil_Futures_Options.xlsx` (Breeden-Litzenberger",
        "risk-neutral densities; smile splined, held flat beyond quoted wings).*",
        "",
        "![](figures/07_iv_smiles.png)",
        "![](figures/07_rnd_densities.png)",
        "",
        "## Tail table (risk-neutral)",
        "",
        tail.round(3).to_markdown(),
        "",
        "## Market-implied probability of the SVAR scenario levels",
        "",
        "Scenario paths converted to nominal USD at a "
        f"{100*CPI_ASSUMPTION:.1f}%/yr CPI assumption:",
        "",
        probs.round(3).to_markdown(),
        "",
        "## Reading",
        "",
        "- Implied vols are at crisis levels (40–65% vs ~30% in calm markets);",
        "  the futures curve is steeply backwardated — the market prices the",
        "  disruption as real but partially resolving over 2026.",
        "- The right tail is heavy and grows with maturity: P(>$120) peaks",
        "  around 7% at ~3–5 months; the 99th percentile reaches ~$150+.",
        "- The left tail is also fat (5th percentile near $50 by year-end):",
        "  the market simultaneously prices resolution + demand destruction.",
        f"- Right/left tail-width ratio (q95 vs q05 distance from F): "
        + ", ".join(f"{k} {v:.2f}" for k, v in skew.items()) + ".",
        "",
        "## Caveats",
        "",
        "- These are *risk-neutral* probabilities: they embed risk premia and",
        "  overstate physical probabilities most in feared states — treat",
        "  P(>$X) as an upper bound.",
        "- Quoted strikes stop near $95–100; beyond them the smile is held",
        "  flat. With a typical upward call skew this likely *understates*",
        "  the extreme right tail. Request wider wings in the next export.",
        "- Single evening snapshot (Australia time); densities move with",
        "  every headline in a crisis. Re-export and re-run for fresh reads.",
    ]
    (REPORTS_DIR / "OPTIONS_TAIL_RISK.md").write_text("\n".join(lines))
    print(f"[report] wrote {REPORTS_DIR / 'OPTIONS_TAIL_RISK.md'}")


def main():
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    chains = orx.parse_chains()
    rnds = [orx.fit_rnd(c) for c in chains]
    for r in rnds:  # martingale sanity check: RN mean ~ future
        drift = abs(r.mean / r.chain.future - 1)
        flag = "" if drift < 0.02 else "  <-- check smile fit"
        print(f"[rnd] {r.chain.label}: F={r.chain.future:.2f} "
              f"E[F]={r.mean:.2f} drift={100*drift:.2f}%{flag}")
    scen = nominal_scenarios()
    smile_figure(chains)
    density_figure(rnds, scen)
    tail = orx.tail_table(rnds)
    probs = scenario_prob_table(rnds, scen)
    tail.to_csv(DATA_PROCESSED / "options_tail_table.csv")
    write_report(rnds, tail, probs)


if __name__ == "__main__":
    main()
